// 결제 화면 문구 키. 서버 페이지가 이 목록대로 messages 의 checkout 네임스페이스를 읽어
// CheckoutForm 에 넘긴다 — 'use client' 파일의 값은 서버에서 못 읽으므로 따로 둔다.
export const CHECKOUT_LABEL_KEYS = [
  'stepOrderer',
  'stepReview',
  'stepContract',
  'stepPay',
  'ordererTitle',
  'ordererHint',
  'name',
  'namePh',
  'phone',
  'phonePh',
  'email',
  'emailPh',
  'postalCode',
  'postalCodePh',
  'addressSearch',
  'address1',
  'address1Ph',
  'address2',
  'address2Ph',
  'representative',
  'representativePh',
  'businessNo',
  'businessNoPh',
  'ordererNote',
  'reviewTitle',
  'reviewHint',
  'editSelection',
  'totalLabel',
  'contractTitle',
  'contractHint',
  'viewContent',
  'viewContract',
  'signatureLabel',
  'signatureNote',
  'payTitle',
  'payCard',
  'payButton',
  'submitting',
  'errorGeneric',
  'close',
  'errRequired',
  'errEmail',
  'errPhone',
  'errSummary',
  'errConsents',
  'contractNeedsOrderer',
] as const

export type CheckoutLabels = Record<(typeof CHECKOUT_LABEL_KEYS)[number], string>
