/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'price-entries': PriceEntry;
    orders: Order;
    'order-transitions': OrderTransition;
    'order-notes': OrderNote;
    'order-schedule-changes': OrderScheduleChange;
    'contract-templates': ContractTemplate;
    inquiries: Inquiry;
    'inquiry-files': InquiryFile;
    quotes: Quote;
    'admin-login-logs': AdminLoginLog;
    'brand-assets': BrandAsset;
    'legal-documents': LegalDocument;
    'legal-revisions': LegalRevision;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'price-entries': PriceEntriesSelect<false> | PriceEntriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-transitions': OrderTransitionsSelect<false> | OrderTransitionsSelect<true>;
    'order-notes': OrderNotesSelect<false> | OrderNotesSelect<true>;
    'order-schedule-changes': OrderScheduleChangesSelect<false> | OrderScheduleChangesSelect<true>;
    'contract-templates': ContractTemplatesSelect<false> | ContractTemplatesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'inquiry-files': InquiryFilesSelect<false> | InquiryFilesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'admin-login-logs': AdminLoginLogsSelect<false> | AdminLoginLogsSelect<true>;
    'brand-assets': BrandAssetsSelect<false> | BrandAssetsSelect<true>;
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    'legal-revisions': LegalRevisionsSelect<false> | LegalRevisionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'pricing-settings': PricingSetting;
    'company-settings': CompanySetting;
  };
  globalsSelect: {
    'pricing-settings': PricingSettingsSelect<false> | PricingSettingsSelect<true>;
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'customer' | 'manager' | 'super';
  name: string;
  phone: string;
  postalCode: string;
  address1: string;
  address2?: string | null;
  businessNo?: string | null;
  termsAgreedAt?: string | null;
  privacyAgreedAt?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-entries".
 */
export interface PriceEntry {
  id: number;
  /**
   * 생성 후에는 변경할 수 없습니다. 계산기·시드 스크립트가 이 키로 단가를 찾습니다.
   */
  key: string;
  labelKo: string;
  labelJa: string;
  category: number;
  priceKrw: number;
  priceJpy: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  paymentId: string;
  idempotencyKey?: string | null;
  status: 'pending' | 'paid' | 'in_progress' | 'done' | 'failed' | 'cancelled' | 'fraud_suspected';
  currency: 'KRW' | 'JPY';
  amount: number;
  locale: 'ko' | 'ja';
  category: number;
  items: {
    code: string;
    label: string;
    unitAmount: number;
    quantity: number;
    id?: string | null;
  }[];
  contractItems: {
    label: string;
    value: string;
    id?: string | null;
  }[];
  country?: ('kr' | 'jp')[] | null;
  purpose?: ('brand' | 'product' | 'store' | 'medical' | 'event' | 'etc') | null;
  customer?: (number | null) | User;
  orderer: {
    name: string;
    phone: string;
    email: string;
    postcode: string;
    address1: string;
    address2?: string | null;
    businessNo?: string | null;
    representative?: string | null;
  };
  signature: string;
  contractText: string;
  sealAsset?: (number | null) | BrandAsset;
  /**
   * 주문 상세의 계약기간 저장 경로로만 변경됩니다. 변경 이력이 남습니다.
   */
  contractStart?: string | null;
  /**
   * 주문 상세의 계약기간 저장 경로로만 변경됩니다. 변경 이력이 남습니다.
   */
  contractEnd?: string | null;
  /**
   * 주문 상세의 계약기간 저장 경로로만 변경됩니다. 변경 이력이 남습니다.
   */
  adStartDate?: string | null;
  paidAt?: string | null;
  failReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-assets".
 */
export interface BrandAsset {
  id: number;
  kind: 'seal';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-transitions".
 */
export interface OrderTransition {
  id: number;
  order: number | Order;
  fromStatus: string;
  toStatus: string;
  actor?: (number | null) | User;
  reason?: string | null;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-notes".
 */
export interface OrderNote {
  id: number;
  order: number | Order;
  body: string;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-schedule-changes".
 */
export interface OrderScheduleChange {
  id: number;
  order: number | Order;
  field: 'contractStart' | 'contractEnd' | 'adStartDate';
  fromValue?: string | null;
  toValue?: string | null;
  actor?: (number | null) | User;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-templates".
 */
export interface ContractTemplate {
  id: number;
  category: number;
  locale: 'ko' | 'ja';
  title: string;
  body: string;
  consents: {
    key: string;
    label: string;
    required: boolean;
    id?: string | null;
  }[];
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  type?: string | null;
  body: string;
  region?: string | null;
  name: string;
  phone: string;
  email: string;
  locale: 'ko' | 'ja';
  customer?: (number | null) | User;
  files?: (number | InquiryFile)[] | null;
  status: 'new' | 'quoted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-files".
 */
export interface InquiryFile {
  id: number;
  originalName?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  quoteNumber: string;
  inquiry: number | Inquiry;
  lines: {
    label: string;
    quantity: number;
    unitAmount: number;
    id?: string | null;
  }[];
  currency: 'KRW' | 'JPY';
  total: number;
  tokenHash: string;
  status: 'issued' | 'revoked';
  issuedAt: string;
  expiresAt: string;
  issuedBy?: (number | null) | User;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-login-logs".
 */
export interface AdminLoginLog {
  id: number;
  user?: (number | null) | User;
  email: string;
  at: string;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  kind: 'terms' | 'privacy';
  locale: 'ko' | 'ja';
  title: string;
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-revisions".
 */
export interface LegalRevision {
  id: number;
  target: 'contract-templates' | 'legal-documents';
  docId: number;
  label: string;
  title: string;
  body: string;
  consents?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  editor?: (number | null) | User;
  editorEmail: string;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'price-entries';
        value: number | PriceEntry;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-transitions';
        value: number | OrderTransition;
      } | null)
    | ({
        relationTo: 'order-notes';
        value: number | OrderNote;
      } | null)
    | ({
        relationTo: 'order-schedule-changes';
        value: number | OrderScheduleChange;
      } | null)
    | ({
        relationTo: 'contract-templates';
        value: number | ContractTemplate;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'inquiry-files';
        value: number | InquiryFile;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'admin-login-logs';
        value: number | AdminLoginLog;
      } | null)
    | ({
        relationTo: 'brand-assets';
        value: number | BrandAsset;
      } | null)
    | ({
        relationTo: 'legal-documents';
        value: number | LegalDocument;
      } | null)
    | ({
        relationTo: 'legal-revisions';
        value: number | LegalRevision;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  phone?: T;
  postalCode?: T;
  address1?: T;
  address2?: T;
  businessNo?: T;
  termsAgreedAt?: T;
  privacyAgreedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-entries_select".
 */
export interface PriceEntriesSelect<T extends boolean = true> {
  key?: T;
  labelKo?: T;
  labelJa?: T;
  category?: T;
  priceKrw?: T;
  priceJpy?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  paymentId?: T;
  idempotencyKey?: T;
  status?: T;
  currency?: T;
  amount?: T;
  locale?: T;
  category?: T;
  items?:
    | T
    | {
        code?: T;
        label?: T;
        unitAmount?: T;
        quantity?: T;
        id?: T;
      };
  contractItems?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  country?: T;
  purpose?: T;
  customer?: T;
  orderer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        postcode?: T;
        address1?: T;
        address2?: T;
        businessNo?: T;
        representative?: T;
      };
  signature?: T;
  contractText?: T;
  sealAsset?: T;
  contractStart?: T;
  contractEnd?: T;
  adStartDate?: T;
  paidAt?: T;
  failReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-transitions_select".
 */
export interface OrderTransitionsSelect<T extends boolean = true> {
  order?: T;
  fromStatus?: T;
  toStatus?: T;
  actor?: T;
  reason?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-notes_select".
 */
export interface OrderNotesSelect<T extends boolean = true> {
  order?: T;
  body?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-schedule-changes_select".
 */
export interface OrderScheduleChangesSelect<T extends boolean = true> {
  order?: T;
  field?: T;
  fromValue?: T;
  toValue?: T;
  actor?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contract-templates_select".
 */
export interface ContractTemplatesSelect<T extends boolean = true> {
  category?: T;
  locale?: T;
  title?: T;
  body?: T;
  consents?:
    | T
    | {
        key?: T;
        label?: T;
        required?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  body?: T;
  region?: T;
  name?: T;
  phone?: T;
  email?: T;
  locale?: T;
  customer?: T;
  files?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiry-files_select".
 */
export interface InquiryFilesSelect<T extends boolean = true> {
  originalName?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  inquiry?: T;
  lines?:
    | T
    | {
        label?: T;
        quantity?: T;
        unitAmount?: T;
        id?: T;
      };
  currency?: T;
  total?: T;
  tokenHash?: T;
  status?: T;
  issuedAt?: T;
  expiresAt?: T;
  issuedBy?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-login-logs_select".
 */
export interface AdminLoginLogsSelect<T extends boolean = true> {
  user?: T;
  email?: T;
  at?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-assets_select".
 */
export interface BrandAssetsSelect<T extends boolean = true> {
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  kind?: T;
  locale?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-revisions_select".
 */
export interface LegalRevisionsSelect<T extends boolean = true> {
  target?: T;
  docId?: T;
  label?: T;
  title?: T;
  body?: T;
  consents?: T;
  editor?: T;
  editorEmail?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings".
 */
export interface PricingSetting {
  id: number;
  periodMultipliers: {
    '1w': number;
    '2w': number;
    '1m': number;
    '3m': number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySetting {
  id: number;
  nameKo: string;
  nameJa: string;
  ceo: string;
  businessNo: string;
  addressKo: string;
  addressJa: string;
  phone: string;
  email: string;
  contactPhone?: string | null;
  mailOrderNo?: string | null;
  sealImage?: (number | null) | BrandAsset;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings_select".
 */
export interface PricingSettingsSelect<T extends boolean = true> {
  periodMultipliers?:
    | T
    | {
        '1w'?: T;
        '2w'?: T;
        '1m'?: T;
        '3m'?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  nameKo?: T;
  nameJa?: T;
  ceo?: T;
  businessNo?: T;
  addressKo?: T;
  addressJa?: T;
  phone?: T;
  email?: T;
  contactPhone?: T;
  mailOrderNo?: T;
  sealImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}